"""empty message

Revision ID: 641c4cf296e5
Revises: 96089780dc64
Create Date: 2022-07-14 08:59:51.050551

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '641c4cf296e5'
down_revision = '96089780dc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('flags_count', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE rounds SET flags_count = 0 WHERE true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'flags_count')
    # ### end Alembic commands ###
