"""empty message

Revision ID: 96089780dc64
Revises: 45811f048651
Create Date: 2022-07-14 08:54:14.167701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96089780dc64'
down_revision = '45811f048651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('funny_count', sa.SmallInteger(), nullable=True))
    op.add_column('rounds', sa.Column('deeep_count', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE rounds SET funny_count = 0 WHERE true")
    op.execute("UPDATE rounds SET deeep_count = 0 WHERE true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'deeep_count')
    op.drop_column('rounds', 'funny_count')
    # ### end Alembic commands ###
