name: Python checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          ruff check .
      - name: Check formatting with black
        uses: psf/black@stable
        with:
          src: "src/ tests/"
          options: "--check --verbose"
      - name: Run unit tests
        run: |
          pytest
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
